import { Plus_Jakarta_Sans } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/Template/Header';
import { Footer } from '@/components/Template/Footer';

const jakarta = Plus_Jakarta_Sans({
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-jakarta',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${jakarta.variable} ${jakarta.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
